# Generated by Django 3.2.9 on 2022-04-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('book_price', models.FloatField()),
                ('book_desc', models.TextField()),
                ('book_image', models.ImageField(default='NO_image', upload_to='product_img/')),
            ],
        ),
    ]
